export enum UserPointLogCategory {
  FIRST_INVITATION_SUCCESS = 'FIRST_INVITATION_SUCCESS',
  FIRST_REPORT_SUBMITTED = 'FIRST_REPORT_SUBMITTED',
  JOINING_VANGUARD_GROUP = 'JOINING_VANGUARD_GROUP',
  FIRST_ACTIVE_WITHIN_24_HOURS = 'FIRST_ACTIVE_WITHIN_24_HOURS',
  FIRST_ACTIVE_WITHIN_3_DAYS = 'FIRST_ACTIVE_WITHIN_3_DAYS',
  FIRST_ACTIVE_AFTER_3_DAYS = 'FIRST_ACTIVE_AFTER_3_DAYS',
  ACTIVE_5_INVITES = 'ACTIVE_5_INVITES',
  ACTIVE_10_INVITES = 'ACTIVE_10_INVITES',
}
